# Generated by Django 3.0 on 2021-05-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210430_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_model',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('birthday', 'birthday'), ('baby shower', 'baby shower'), ('well come baby', 'well come baby'), ('anniversary', 'anniversary'), ('haldi', 'haldi'), ('ring ceremony', 'ring ceremony'), ('grand opening', 'grand opening'), ('mehndi', 'mehndi')], max_length=100),
        ),
    ]
